# Generated by Django 3.1 on 2021-01-19 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics communication and Engineering'), ('CE', 'Civil Engineering'), ('EEE', 'Electrical Engineering'), ('EIE', 'Electronics & Instrumentation Engineering'), ('ME', 'Mechanical Engineering')], max_length=100)),
                ('phone_number', models.PositiveIntegerField()),
                ('designation', models.CharField(choices=[('HOD', 'Head of Department'), ('AP', 'Associate Professor'), ('P', 'Professor')], max_length=100)),
                ('employee_number', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
